# Generated by Django 5.0 on 2023-12-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
