# Generated by Django 5.0 on 2023-12-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='residence_name',
        ),
    ]
