# Generated by Django 5.0 on 2023-12-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='residence_name',
        ),
        migrations.AddField(
            model_name='product',
            name='flat_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='floor_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='room_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
