# Generated by Django 5.0 on 2024-01-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_residence_name_product_flat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
    ]
